name: Update Photo

on:
  push:
    branches:
      - main

jobs:
  update_photo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: pip install Pillow 
      
    - name: Run Python script
      run: python update_photo.py 
      
    - name: Commit changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add photo.png
        git commit -m "Update photo.png with new .png" 
        git push
